# Generated by Django 5.0.6 on 2024-09-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aportes',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='asociado',
            name='fecha_de_nacimiento',
            field=models.DateField(),
        ),
    ]
